function printEqualizerSummary(equalizerDetails, outputAnalysis, stability)
%PRINTEQUALIZERSUMMARY Print gain, output-level, and BIBO-stability results.

fprintf("\nStep 3: Parallel equalizer output\n");
for bandIndex = 1:numel(equalizerDetails.bandNames)
    fprintf("  %s gain: %+g dB (linear %.4f), branch peak: %.6f\n", ...
        equalizerDetails.bandNames(bandIndex), ...
        equalizerDetails.gainDB(bandIndex), ...
        equalizerDetails.gainLinear(bandIndex), ...
        equalizerDetails.branchPeak(bandIndex));
end
fprintf("  Output peak before peak management: %.6f\n", ...
    equalizerDetails.outputPeakBeforeManagement);
fprintf("  Peak management: %s, applied: %s, scale: %.6f\n", ...
    equalizerDetails.peakManagementMode, ...
    string(equalizerDetails.peakManagementApplied), equalizerDetails.outputScale);
fprintf("  Output peak after peak management: %.6f\n", equalizerDetails.outputPeak);

fprintf("\nBIBO stability\n");
for bandIndex = 1:numel(stability.bandNames)
    fprintf("  %s max |pole|: %.6f\n", stability.bandNames(bandIndex), ...
        stability.branchMaxPoleMagnitude(bandIndex));
end
fprintf("  Stable for all finite gains in the configured range: %s\n", ...
    string(stability.isBIBOStable));
fprintf("  Reason: %s\n", stability.reason);

fprintf("\nEqualized output levels\n");
for channelIndex = 1:outputAnalysis.channelCount
    fprintf("  Channel %d: peak = %.6f (%.2f dBFS), RMS = %.6f (%.2f dBFS)\n", ...
        channelIndex, outputAnalysis.peakPerChannel(channelIndex), ...
        outputAnalysis.peakDBFSPerChannel(channelIndex), ...
        outputAnalysis.rmsPerChannel(channelIndex), ...
        outputAnalysis.rmsDBFSPerChannel(channelIndex));
end
end
